source "https://rubygems.org"

gem "double_doc", :path => File.join(File.expand_path(File.dirname(__FILE__)), "..", "..")
gem "zendesk_api", :git => "https://github.com/zendesk/zendesk_api_client_rb.git", :ref => "v0.3.2"
