source "https://rubygems.org"

gem "double_doc", :path => File.join(File.expand_path(File.dirname(__FILE__)), "..", "..")
gem "zendesk_configuration", :git => "git@github.com:zendesk/zendesk_configuration.git", :ref => "v1.1.1"
